# -*- coding: utf-8 -*-
from __future__ import division, print_function, absolute_import
import os

ROOT_PATH = ''

DATASET_NAME = 'hooks'
GPU_GROUP = '0'

NET_NAME = 'resnet_v1_50'
SAVE_MODEL_PATH = ROOT_PATH + 'result/model'
VERSION = '1'
PRETRAINED_MODEL_PATH = ROOT_PATH + 'input/pretrained_model/' + NET_NAME + '.ckpt'
SUMMARY_PATH = ROOT_PATH + 'result/summary'
INFERENCE_IMG_PATH = ROOT_PATH + 'data/inference'
INFERENCE_RESULT_PATH = ROOT_PATH + 'result/inference'

LABEL_HORIZEN = True
LABEL_INCLINED = False

CLASS_NUM = 7

BATCH_SIZE = 1
SHORT_SIDE_LEN = 600

FEATURE_WEIGHT_DECAY = 0.00001
STRIDE = 16

USE_FPN = False
LEVEL = ['P2', 'P3', 'P4', 'P5', 'P6']
BASE_ANCHOR_SIZE_LIST = [32., 64., 128., 256., 512.]
if USE_FPN:
    STRIDE = [4, 8, 16, 32, 64]

T_SCALE = [10., 10., 5., 5.]

ANCHOR_SCALES = [128., 256., 512.]
ANCHOR_RATIOS = [1/2., 1.0, 2.0]
REMOVE_OUTSIDES_ANCHORS = True
RPN_POSITIVE_THRESHOLD = 0.7
RPN_NEGATIVE_THRESHOLD = 0.3
RPN_MINIBATCH_SIZE = 256
RPN_MINIBATCH_POSITIVE_RATIO = 0.5
TOPK_NUM = 6000
RPN_NUM = 1000
NMS_THRESHOLD = 0.7
RPN_LOSS_LAMBDA = 10.

ROI_SIZE = 7
FAST_RCNN_POSITIVE_THRESHOLD = 0.5
FAST_RCNN_MINIBATCH_SIZE = 128
FAST_RCNN_MINIBATCH_POSITIVE_RATIO = 0.25
BOX_NUM_EACH_CLASS = 20
NMS_THRESHOLD_EACH_CLASS = 0.15
SHOW_BOXES_THRESHOLD = 0.9
FAST_RCNN_LOSS_LAMBDA = 1.

MOMENTUM = 0.9
BASE_LR = 0.001
MAX_ITERATION = 50000
SNAPSHOT_STEP = 20
SAVE_MODEL_STEP = 5000

